configReload:
  configUrl: https://raw.githubusercontent.com/sallyom/fetchit-config/main/config.yaml
  schedule: "*/2 * * * *"
targetConfigs:
- name: example
  url: https://github.com/sallyom/fetchit-config
  trackBadCommits: true
  fileTransfer:
  - name: hello
    targetPath: filetransfer
    destinationDirectory: /tmp/filetransfer
    schedule: "*/1 * * * *"
  branch: main
